### ISSUE TITLE
How to get a SSL cert for your locally hosted app

### ISSUE THREAD

**Issue by benhylau** [dweb-camp-2019/meshnet#11]

**Comment by benhylau** [comment]
@ansuz and I talked about connecting to Internet to get a cert, and then run offline. Somehow this feels like cheating a little... although the expectation is "we have some internet" not "no internet".

Is self-signed an option?

Relevant https://github.com/FiloSottile/mkcert

**Comment by darkdrgn2k** [comment]
Create your own CA
- https://deliciousbrains.com/ssl-certificate-authority-for-local-https-development/

Install CA certificate on devices

ios- https://www.ibm.com/support/knowledgecenter/ja/SSHS8R_6.3.0/com.ibm.worklight.installconfig.doc/admin/t_installing_root_CA_iOS.html

Issue certs signed by local CA

**Comment by ansuz** [comment]
Having people install a new CA on their machine is a bit risky. If they don't remove the cert after the camp, we could conceivably abuse that cert. They'd be trusting us not to do [something like Sennheiser](https://www.digitaltrends.com/computing/sennheisers-flawed-headphone-utility-is-a-trojan-horse-in-disguise/).

**Comment by ansuz** [comment]
https://security.stackexchange.com/questions/71632/how-bad-it-is-to-install-another-companys-root-certificate-to-your-server

**Comment by darkdrgn2k** [comment]
> https://security.stackexchange.com/questions/71632/how-bad-it-is-to-install-another-companys-root-certificate-to-your-server

Many firewalls out there that do malware detection cannot (for obvious reasons) inspect SSL.  Many companies require you to install their root CA so that their deep packet inspection firewall can deal decrypt, inspect and re-encrypt your data.   This is horrible as it breaks what ssl should be! This also impersonates the real certificates and because your proxied there is no way to tell if the site cert is real or not.

On the other hand some environments (Microsoft Active Directory) build  CA as part of the install process. This allows the servers to generate certificates against all the computer on the network so that each device has a unique SSL cert and unique keys to enhance security.  Obviously in this model you HAVE to trust that your domain controller is good. But as its a controlled environment, they usually are.

Also you dont need to be a "unauthorized" root CA to be distrusted. Enter the [symantec scandal](https://www.wordfence.com/blog/2018/09/reminder-popular-browsers-to-distrust-symantec-ssl-tls-certificates-starting-in-october/)


> Having people install a new CA on their machine is a bit risky.

Yes trusting a root cert is all about trusting the person who holds the keys to it. The ROOT certs you have installed in your OS are there because only a few big fish hold the keys to all the SSL certs in the world. Look at letsencrypt that tried to get signed by one of the "big ones".  It was somewhat of a headache.

> If they don't remove the cert after the camp, we could conceivably abuse that cert. 

Have the CA Cert expire after DWeb and all the certs signed by it to expire at that time as well. Then all the ssl certs would be null and void by the time DWeb is over.


Then you wipe all copies of the private key of the CA.

Just some counter points.  Building a CA is a big responsibility and should not be taken lightly.
Thanks @ansuz for making sure we remember that

**Comment by amark** [comment]
self-signed cert is possible, but on most browsers you have to click pass the "PROCEED WITH CAUTION!" warnings and this is especially nasty (hard to do) on mobile.

SSL/HTTPS is unfortunately necessary to get access to most Browser-based cryptography (WebCrypto), so without it ... could cause problems.

However, for bootstrapping, it should be possible to have `http` people can access, which then lets people download native apps that have access to crypto libraries. Then people don't need to install/modify anything ahead of time, they can show up at the conference and roll.

**Comment by benhylau** [comment]
It looks like we will have Internet access for most of the day, so probably SSL isn't such a big deal as "getting a cert" will probably happen during those hours outside of our [planned Internet outage](https://github.com/dweb-camp-2019/meshnet/issues/12#issuecomment-501920788).

**Comment by benhylau** [comment]
Turns out not be needed as we mostly have Internet service and the local services are over http.
