### ISSUE TITLE
Raspbian Buster busted IP forwarding

### ISSUE THREAD

**Issue by benhylau** [dweb-camp-2019/meshnet#23]
Everything seems to work in newly released [Raspbian Buster Lite](https://www.raspberrypi.org/blog/buster-the-new-version-of-raspbian/) except ifaces don't forward https://github.com/dweb-camp-2019/meshnet/blob/master/testnet/install#L18-L21

Workaround? Download Stretch Lite

**Comment by YurkoWasHere** [comment]
tomesh prototype -  Devel branch with Babeld-tomesh package (installed manually since it does not "support" buster yet in the repo)

modified mesh-point to assing an ip address to the wlan0
kill wpa_supplicant
Change ip address of access point and  remove WPA
flush firewall rules `iptables -F -t nat; iptables -F; ip6tables -F -t nat; ip6tables -F`

![image](https://user-images.githubusercontent.com/39072689/60357588-03433a80-99a2-11e9-949b-e00fd5eb8225.png)

```
PING 10.10.9.46 (10.10.9.46): 56 data bytes
64 bytes from 10.10.9.46: seq=0 ttl=63 time=5.514 ms
64 bytes from 10.10.9.46: seq=1 ttl=63 time=35.455 ms
64 bytes from 10.10.9.46: seq=2 ttl=63 time=173.897 ms

```

**Comment by darkdrgn2k** [comment]
tomesh prototype -  Devel branch with Babeld-tomesh package (installed manually since it does not "support" buster yet in the repo)

modified mesh-point to assing an ip address to the wlan0
kill wpa_supplicant
Change ip address of access point and  remove WPA
flush firewall rules `iptables -F -t nat; iptables -F; ip6tables -F -t nat; ip6tables -F`

![image](https://user-images.githubusercontent.com/29005789/60357850-b7dd5c00-99a2-11e9-9840-54703cd69f47.png)

*note* babeld network is a bunch of nodes running babeld but im pritty sure this is a direct link over meshpoint

```
PING 10.10.9.46 (10.10.9.46): 56 data bytes
64 bytes from 10.10.9.46: seq=0 ttl=63 time=5.514 ms
64 bytes from 10.10.9.46: seq=1 ttl=63 time=35.455 ms
64 bytes from 10.10.9.46: seq=2 ttl=63 time=173.897 ms

```

```
traceroute to 10.10.9.46 (10.10.9.46), 30 hops max, 38 byte packets
 1  10.102.35.79 (10.102.35.79)  1.164 ms  0.974 ms  2.032 ms
 2  *  10.10.9.46 (10.10.9.46)  4.896 ms  2.964 ms
root@NODE152-206:~#
```

**Comment by darkdrgn2k** [comment]
So it looks like DHCPCD is eating your IPV6 address because it thinks its assigned to WLAN0
```
Jun 30 06:24:15 raspberrypi dhcpcd[554]: mesh0: removing interface
Jun 30 06:24:15 raspberrypi dhcpcd[554]: mesh0: deleting address fe80::ea14:1281:91fc:bd05
Jun 30 06:24:15 raspberrypi dhcpcd[554]: mesh0: IAID eb:13:76:3a
Jun 30 06:24:15 raspberrypi dhcpcd[554]: mesh0: IAID conflicts with one assigned to wlan0
Jun 30 06:24:15 raspberrypi dhcpcd[554]: mesh0: adding address fe80::ea14:1281:91fc:bd05
Jun 30 06:24:15 raspberrypi dhcpcd[554]: mesh0: removing interface
```

Simple solution would to put mesh0 back to wlan0 (this is the second version update that broke mesh0, we had to do the same in prototype when moving to stretch)

**Comment by benhylau** [comment]
Thanks for looking into this. When I did the rename I knew I'd regret this one day...
Something like this? https://github.com/dweb-camp-2019/meshnet/commit/52376410b372cf1f3f1084f970212b59c5d62fc5

It's okay to push untested code directly to production if the code is in a folder called `testnet` right? 😉

**Comment by benhylau** [comment]
Think this is fixed, just needs verification before closing.

**Comment by benhylau** [comment]
I'll assume this is fixed :)
